server
 port: 8081
 servlet.context-patch: /projetocontrole

spring
 h2.console
  enabled: true
  path: /h2-console

spring
 datasource
  url: jdbc:h2:file:C:/DEV/eclipse-workspace/database/data
  username: sa
  password:
  driver-class-name: org.h2.Driver
  jpa.hibernate.ddl-auto: update
